mod advanced;
mod breakout;
mod dual_sma;
mod dynamic;
mod ensemble;
mod mean_reversion;
mod momentum;
mod order_flow;
mod smc;
pub mod strategy_factory;
pub mod strategy_selector;
mod traits;
pub mod trend_riding;
mod vwap;

pub use advanced::{AdvancedTripleFilterConfig, AdvancedTripleFilterStrategy};
pub use breakout::BreakoutStrategy;
pub use dual_sma::DualSMAStrategy;
pub use dynamic::{DynamicRegimeConfig, DynamicRegimeStrategy};
pub use ensemble::EnsembleStrategy;
pub use mean_reversion::MeanReversionStrategy;
pub use momentum::MomentumDivergenceStrategy;
pub use order_flow::OrderFlowStrategy;
pub use smc::SMCStrategy;
pub use strategy_factory::StrategyFactory;
pub use traits::{AnalysisContext, Signal, TradingStrategy};
pub use trend_riding::TrendRidingStrategy;
pub use vwap::VWAPStrategy;
