#!/bin/bash
# Research latest trading best practices
# Usage: ./research_latest.sh
#
# This script provides prompts for web research on current trading practices

echo "=================================================="
echo "📚 Trading Best Practices Research"
echo "=================================================="
echo ""
echo "Use these search queries to research latest practices:"
echo ""
echo "1. Algorithmic Trading:"
echo "   - 'algorithmic trading best practices 2026'"
echo "   - 'quantitative trading risk management'"
echo "   - 'systematic trading strategies performance'"
echo ""
echo "2. Risk Management:"
echo "   - 'position sizing algorithms'"
echo "   - 'portfolio risk management techniques'"
echo "   - 'drawdown protection strategies'"
echo ""
echo "3. Market Microstructure:"
echo "   - 'market microstructure changes 2026'"
echo "   - 'execution algorithms best practices'"
echo "   - 'slippage reduction techniques'"
echo ""
echo "4. Regulatory:"
echo "   - 'SEC algorithmic trading regulations'"
echo "   - 'FINRA automated trading rules'"
echo ""
echo "5. Academic Research:"
echo "   - 'SSRN algorithmic trading'"
echo "   - 'arXiv quantitative finance'"
echo ""
echo "=================================================="
echo "After research, document findings in:"
echo "  .agent/skills/trading-best-practices/research/"
echo "=================================================="
